### ISSUE TITLE
[todo] 사용하지 않는 코드 및 패키지 정리

### ISSUE THREAD

**Issue by JuneParkCode** [manito42/FrontEnd#152]
## Todo
- [ ] 사용하지 않는 컴포넌트, 페이지 정리
- [ ] 필요한 패키지 분리
- [ ] yarn cache repository 에서 제거
