### ISSUE TITLE
[todo] fix - title, dark mode

### ISSUE THREAD

**Issue by JuneParkCode** [manito42/FrontEnd#181]
## 분류
- fix

## 목표
- 42 mainto 로 표기된 title을 42Manito로 오타 수정
- light mode 강제

## 기한
- 09.25.23

## 할 일
- [x] app.tsx 의 title 변경
- [x] localStorage 의 theme을 light로 강제
- [x] footer의 darkmode toggle 삭제
