### ISSUE TITLE
[todo] 멘토링 취소 모달 개발

### ISSUE THREAD

**Issue by JuneParkCode** [manito42/FrontEnd#190]
## 분류
- feature

## 목표
- 멘토링 취소 모달 개발
<img width="414" alt="image" src="https://github.com/manito42/FrontEnd/assets/81505228/c3f6caca-3c9b-493d-80b1-09c608ebcef5">
<img width="398" alt="image" src="https://github.com/manito42/FrontEnd/assets/81505228/01a111ad-d2b9-4c24-8158-7a9b7a95e632">
- 위 모달처럼 취소하기 버튼 클릭 시 해당 모달이 나타날 수 있도록 변경함
- #180 

## 기한
- 23.10.03

## 할 일
- [ ] 멘토링 취소 모달 개발
- [ ] 멘토링 취소 버튼과 모달 연동
- [ ] home 에서도 해당 모달을 볼 수 있도록 변경

## 추가 설명
- 기존 모달 형태를 사용합니다.
- 가능하다면, 모달의 스타일 컴포넌트를 별도로 개발하여 다른 작은 모달에서도 적용할 수 있도록 사용합니다.

**Comment by JuneParkCode** [comment]
@koreanddinghwan 님하고 api 관련하여 이야기 나누고 진행하셔야합니다

**Comment by koreanddinghwan** [comment]
취소 사유에 대해서 프론트에서 렌더링하실 예정인가요?

**Comment by JuneParkCode** [comment]
렌더링 필요하지 않을까 싶은데, 그러면 할 일에 예약 컴포넌트에서 optional 하게 취소사유 추가 해야합니다

**Comment by koreanddinghwan** [comment]
NULL로직이 추가되는 것보다는 디폴트로 사유를 선택할 수 있게하는건 어떤가요
1. 시간이 맞지 않아 취소합니다.
2. 멘토/멘티로부터 연락이 없어 취소합니다.
3. 기타(직접입력)

요런식으로요

**Comment by JuneParkCode** [comment]
전 그거 괜찮다고 생각합니다
@falconlee236 전담 부분이시니 의견 꼭 부탁드리고
@obvoso @jinaji 님도 의견 따로 있으시면 부탁드려여(없으면 그냥 이모지만..)

**Comment by obvoso** [comment]
너무 좋은 의견 같아여

**Comment by jinaji** [comment]
너무 좋은 의견이에요

**Comment by falconlee236** [comment]
좋은 의견 감사합니다
기존에 있는 카테코리에서 버튼 누르면 선택할수있는 창이 나오는것처럼 구현하면 될거 같아요

**Comment by koreanddinghwan** [comment]
감사합니다
