### ISSUE TITLE
[todo] 프로필의 관심분야 / 멘토링 분야 클릭시 search 로 이동

### ISSUE THREAD

**Issue by JuneParkCode** [manito42/FrontEnd#191]
## 분류
- feat

## 목표
-  <img width="573" alt="image" src="https://github.com/manito42/FrontEnd/assets/81505228/a1d41510-ef94-46fb-8f20-bb9852c617f6">
- 위 버튼 클릭시 /Search/:name 페이지로 이동
- #172 

## 기한
- 23.10.03

## 할 일
- [ ]  카테고리 버튼 클릭시 Search 이동
- [ ]  해시태그 버튼 클릭시 Search 이동
- [ ] 카테고리 버튼 hover 시 cursor-pointer 설정

## 추가 설명
- 해당 컴포넌트들이 ProfileUpdate 와 엮여있어 작업에 유의해야합니다.
