### ISSUE TITLE
[todo] 멘토링 확인 프로세스 변경

### ISSUE THREAD

**Issue by JuneParkCode** [manito42/FrontEnd#226]
## 분류
- fix

## 목표
- 확인하기 버튼을 진행하기 버튼으로 변경
- 진행하기 버튼 클릭 시 두 가지 동작 발생
  - slack dm link 를 새 탭으로 제공 (이동할지 물어봐야할듯?)
  - backend 에서는 이메일로 해당 정보를 멘티에게 제공
- 멘토 프로필에서 slack dm link 관련 정보 수정 제공
  - dm link의 형식을 파악하고 해당 형식으로 입력하는지 알려줘야함
  - ? 버튼 하나 제공해서 어떻게 받아오는지 알려주는 가이드로 리디렉션할 수 있도록 하면 더 좋을 것 같음.

## 기한
- 10.04

## 할 일
- [ ] 확인하기 버튼을 진행하기 버튼으로 변경
- [ ] slack dm link 을 멘토 프로필 변경 과정에서 받아올 수 있도록 함.
- [ ] 진행하기 버튼 클릭 시 해당 링크로 이동

## 추가 설명
- @koreanddinghwan 님과의 작업이 같이 이루어져야합니다.

**Comment by koreanddinghwan** [comment]
<img width="733" alt="Screen Shot 2023-10-01 at 4 24 51 PM" src="https://github.com/manito42/FrontEnd/assets/76278794/d6a2db72-3746-4f17-8f1c-c92551ef317a">

- 프론트
슬랙 아이디=> profiles 페이지에서만 렌더링/home에서 타고들어가서 보이는 멘토정보에서는 x
슬랙 아이디 수정창=> 관심분야 <->소개글 사이에
멘토로 활동하기 버튼누를때 slack 경로 있는지 검증

**Comment by jinaji** [comment]
<img width="351" alt="image" src="https://github.com/manito42/FrontEnd/assets/101309869/e11873b7-98e8-44a8-a8d1-c0076f06ed29">
</br>
나의 프로필 페이지
</br>

<img width="332" alt="image" src="https://github.com/manito42/FrontEnd/assets/101309869/f4bf3684-0d4e-427f-9d4f-1ab74aeff94d">
</br>
다른 사람 프로필 페이지
</br>

<img width="315" alt="image" src="https://github.com/manito42/FrontEnd/assets/101309869/432fea88-e963-48f8-9b81-388b3b19ff52">
</br>
메인 홈 멘토카드
</br>

디자인은 요렇게 될 것 같아여
프로퍼티 ... slackProfileLink ... 우떠신지
DTO랑 api 나오면 연결할게여 ~~

**Comment by JuneParkCode** [comment]
- #155

**Comment by koreanddinghwan** [comment]
> <img alt="image" width="351" src="https://user-images.githubusercontent.com/101309869/271816195-e11873b7-98e8-44a8-a8d1-c0076f06ed29.png">
> 나의 프로필 페이지
> <img alt="image" width="332" src="https://user-images.githubusercontent.com/101309869/271816443-f4bf3684-0d4e-427f-9d4f-1ab74aeff94d.png">
> 다른 사람 프로필 페이지
> <img alt="image" width="315" src="https://user-images.githubusercontent.com/101309869/271816223-432fea88-e963-48f8-9b81-388b3b19ff52.png">
> 메인 홈 멘토카드
> 디자인은 요렇게 될 것 같아여 프로퍼티 ... slackProfileLink ... 우떠신지 DTO랑 api 나오면 연결할게여 ~~

slack 아이콘 사용해도 좋을것같아용

**Comment by koreanddinghwan** [comment]
@JuneParkCode 확장성 고려해서 설계할까요 아니면, 링크 1개만 받을 수 있게끔할까요?

**Comment by JuneParkCode** [comment]
확장성이 좋을 것 같긴한데.. 일단은 slack dm 은 필수라고 치고 하나만 해봅시다.

**Comment by JuneParkCode** [comment]
근데 이렇게 되면 슬랙 dm url 을 필수 요소로 둬야하나 싶네요. (멘토 프로필 활성화 시에)

**Comment by koreanddinghwan** [comment]
> 근데 이렇게 되면 슬랙 dm url 을 필수 요소로 둬야하나 싶네요. (멘토 프로필 활성화 시에)

그거 validation추가하려고합니다 백엔드에서는요

**Comment by jinaji** [comment]
> slack 아이콘 사용해도 좋을것같아용

슬랙 링크 밑에 아이콘 놓고 링크 연결 말씀하시는 건가염? 아이콘으로 넣을 거면 푸터에 SNS 링크 넣을 때처럼 멘토 토글 옆에 넣어도 될 것 같기도 하고 ,,, 


> 근데 이렇게 되면 슬랙 dm url 을 필수 요소로 둬야하나 싶네요. (멘토 프로필 활성화 시에)

뮤님이 말씀주셔서 토글 켜려면 url 두는 쪽으로 작업해보기로 했어여 근데 dm으로 바로 연결되는 url이 있을까용? 저희 아까 이야기 나눈 링크는 프로필로 연결되는 것 같아염

**Comment by koreanddinghwan** [comment]
> > slack 아이콘 사용해도 좋을것같아용
> 
> 슬랙 링크 밑에 아이콘 놓고 링크 연결 말씀하시는 건가염? 아이콘으로 넣을 거면 푸터에 SNS 링크 넣을 때처럼 멘토 토글 옆에 넣어도 될 것 같기도 하고 ,,,
> 
이것도 괜찮은듯


> > 근데 이렇게 되면 슬랙 dm url 을 필수 요소로 둬야하나 싶네요. (멘토 프로필 활성화 시에)
> 
> 뮤님이 말씀주셔서 토글 켜려면 url 두는 쪽으로 작업해보기로 했어여 근데 dm으로 바로 연결되는 url이 있을까용? 저희 아까 이야기 나눈 링크는 프로필로 연결되는 것 같아염

DM으로 연결되는건 없어용..프로필로만갑니다

**Comment by koreanddinghwan** [comment]
https://42born2code.slack.com/team/U035K1WFM6H 근데 이걸 어떻게 처리해야하지...

**Comment by koreanddinghwan** [comment]
https://42born2code.slack.com/team/U035K1WFM6H

**Comment by koreanddinghwan** [comment]
https://github.com/manito42/FrontEnd/assets/76278794/032dbcba-9c33-4cc0-9bff-7594f696470e


데스크톱에서는 slack있으면 잘 열리네요
