### ISSUE TITLE
[todo] search 오류 수정

### ISSUE THREAD

**Issue by JuneParkCode** [manito42/FrontEnd#238]
## 분류
- fix

## 목표
- Search 에서 발생하는 오류 제거
  - 재검색시 결과가 나오지않는 문제
  - 모바일 환경에서 검색 이후 사이드바가 사라지지 않는 문제
  - 검색 바가 데스크톱 환경에서 헤더와 페이지에 동시에 존재하는 문제
- #170 

## 기한
- 10.05.

## 할 일
- [ ] 모바일에서 사이드 바를 통한 검색시 검색 이후 사이드바가 사라지도록 함
- [ ] 같은 단어를 두 번 검색하는 경우 검색 결과가 사라지는 문제를 해결
- [ ] 검색 결과에서 검색바가 모바일 환경에서만 노출되도록 함.

## 추가 설명
- 해당 작업에 대한 추가 설명을 작성해주세요
